version: '3.8'
services:
  backend:
    image: docker/k8s-transfer-backend:1.1
    container_name: k8s-transfer-backend
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_PATH=/app/data/k8s-transfer.db
      - CORS_ORIGIN=https://new-cluster-domain.ril.com
    volumes:
      - db_data:/app/data
    ports:
      - "3001:3001"

  frontend:
    image: docker/frontend:1.1
    container_name: k8s-transfer-frontend
    restart: always
    ports:
      - "3002:80"
    depends_on:
      - backend

volumes:
  db_data:
    name: k8s-transfer-db
